### ISSUE TITLE
TypeError: Invalid host defined options when Importing

### ISSUE THREAD

**Issue by peter-neumann-dev** [tborychowski/gulp-rollup-plugin#1]
Hi @tborychowski!

Thanks for already providing a plugin for rollup that supports v3 of rollup! 🎉 

Unfortunately, when I try to import the module in my Gulpfile with `import rollup from 'gulp-rollup-plugin'` I already get an error:

```bash
Requiring external module esm
TypeError: Invalid host defined options
    at eval (eval at <anonymous> (/Users/peterneumann/dev/buffdist-v10/node_modules/gulp-cli/lib/shared/require-or-import.js:10:15), <anonymous>:3:1)
    at requireOrImport (/Users/peterneumann/dev/buffdist-v10/node_modules/gulp-cli/lib/shared/require-or-import.js:24:7)
    at execute (/Users/peterneumann/dev/buffdist-v10/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
    at Liftoff.handleArguments (/Users/peterneumann/dev/buffdist-v10/node_modules/gulp-cli/index.js:211:24)
    at Liftoff.execute (/Users/peterneumann/dev/buffdist-v10/node_modules/liftoff/index.js:201:12)
    at module.exports (/Users/peterneumann/dev/buffdist-v10/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Users/peterneumann/dev/buffdist-v10/node_modules/liftoff/index.js:191:5)
    at /Users/peterneumann/dev/buffdist-v10/node_modules/liftoff/index.js:149:9
    at /Users/peterneumann/dev/buffdist-v10/node_modules/v8flags/index.js:162:14
    at /Users/peterneumann/dev/buffdist-v10/node_modules/v8flags/index.js:41:14
```

Do you have an idea? 🙂

**Comment by tborychowski** [comment]
Ha!
Didn't realise anyone else would use this 😬
I only wrapped rollup for my own projects to have a cleaner gulpfile. 

Anyway, could you post the relevant part of your gulpfile (where the plugin is called), so I have a better idea how you use it?
And maybe the versions of the relevant 'devDependencies' from your `package.json`? (just want to check which version is your gulp, rollup, and other plugins, just in case).

**Comment by peter-neumann-dev** [comment]
Yes, that's exactly what I wanted to achieve again too! Previously I used https://www.npmjs.com/package/gulp-best-rollup-2 but as the name suggests it only support Rollup 2.

It's interesting because it seems that right after the import with or without using it the TypeError appears. Here is my setup:

package.json
```json
"devDependencies": {
	"@rollup/plugin-legacy": "^3.0.1",
	"@rollup/plugin-node-resolve": "^15.0.1",
	"autoprefixer": "^10.4.13",
	"cssnano": "^5.1.14",
	"eslint": "^8.27.0",
	"eslint-config-jquery": "^3.0.0",
	"eslint-config-standard": "^17.0.0",
	"eslint-plugin-compat": "^4.0.2",
	"esm": "^3.2.25",
	"gulp": "^4.0.2",
	"gulp-if": "^3.0.0",
	"gulp-plumber": "^1.2.1",
	"gulp-postcss": "^9.0.1",
	"gulp-rename": "^2.0.0",
	"gulp-rollup-plugin": "^2.0.0",
	"gulp-sass": "^5.1.0",
	"gulp-sourcemaps": "^3.0.0",
	"gulp-uglify": "^3.0.2",
	"npm": "^8.19.3",
	"postcss": "^8.4.18",
	"rollup": "^3.2.5",
	"sass": "^1.56.0",
	"stylelint": "^14.14.1",
	"stylelint-config-standard-scss": "^6.1.0",
	"stylelint-group-selectors": "^1.0.9",
	"stylelint-scss": "^4.3.0",
	"yargs": "^17.6.2"
},
```

And this is my gulp task:
```javascript
const buildJS = () => {
  return src(files.js)
    .pipe(gulpif(!isProduction, plumber()))
    .pipe(gulpif(!isProduction, sourcemaps.init()))
    .pipe(rollup({ plugins: [nodeResolve()] }, { format: 'iife' }))
    .pipe(uglify())
    .pipe(rename({ suffix: '.min' }))
    .pipe(gulpif(!isProduction, sourcemaps.write('')))
    .pipe(dest(paths.destJS))
}
```

But as I mentioned, it happens right after importing. 🤔
(Node 18)

**Comment by peter-neumann-dev** [comment]
When I delete my modules, the first error message is slightly different:
```bash
[20:34:27] Requiring external module esm
TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
    at new NodeError (node:internal/errors:387:5)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
    at eval (eval at <anonymous> (/Users/peterneumann/dev/buffdist-v10/node_modules/gulp-cli/lib/shared/require-or-import.js:10:15), <anonymous>:3:1)
    at requireOrImport (/Users/peterneumann/dev/buffdist-v10/node_modules/gulp-cli/lib/shared/require-or-import.js:24:7)
    at execute (/Users/peterneumann/dev/buffdist-v10/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
    at Liftoff.handleArguments (/Users/peterneumann/dev/buffdist-v10/node_modules/gulp-cli/index.js:211:24)
    at Liftoff.execute (/Users/peterneumann/dev/buffdist-v10/node_modules/liftoff/index.js:201:12)
    at module.exports (/Users/peterneumann/dev/buffdist-v10/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Users/peterneumann/dev/buffdist-v10/node_modules/liftoff/index.js:191:5)
    at /Users/peterneumann/dev/buffdist-v10/node_modules/liftoff/index.js:149:9 {
  code: 'ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING'
}
```

I also tried rollup version 3.1.0 just in case, but it's not related to that.

**Comment by tborychowski** [comment]
Hi again,

I'm trying to reproduce this issue but cannot (on 2 different macs).
I have the same versions of dependencies, matched your gulpfile config and everything works fine :-|

One more thing to check, if you don't mind: are you using `gulpfile.mjs` or have `"type": "module"` in your `package.json`? (`import` statements need one or the other) - and if it's the former, would you mind trying to add the `"type": "module"` to your `package.json` and see if it makes any difference?

If not, would it be possible to create a stripped-down version of your project (e.g. as a separate repo that I could clone) so I can reproduce this?

Your error stack doesn't show any of the plugin files, which makes me think it may be something else with the setup...

**Comment by peter-neumann-dev** [comment]
Hi @tborychowski, thank you for all investigations.

This drives me crazy. I was just about to install chalk in version 5 and the same error occurred. Since version 4 they switched to pure ESM. After I have fixed my `package.json` and defined it as `"type": "module"` it is now working both with your plugin and chalk@5

Thank you 👍 Issue can be closed ✅

**Comment by tborychowski** [comment]
That's great! Thanks!
